version: '3.8'

services:
  db:
    container_name: shouter_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shouter
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  postgres-data:
